# Generated by Django 6.0.1 on 2026-01-18 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='valid_id',
        ),
    ]
