# Generated by Django 6.0.1 on 2026-02-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='valid_id',
            field=models.ImageField(blank=True, null=True, upload_to='valid_ids/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='program',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('IS', 'Information Systems'), ('CE', 'Data Science')], max_length=2),
        ),
    ]
