# Generated by Django 6.0.1 on 2026-02-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
