# Generated by Django 6.0.1 on 2026-02-03 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('module', models.CharField(choices=[('User Management', 'User Management'), ('Event Management', 'Event Management'), ('Job & Internship', 'Job & Internship'), ('CMS & News Feed', 'CMS & News Feed'), ('Fundraising', 'Fundraising'), ('Feedback & Surveys', 'Feedback & Surveys')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Completed', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
