# Generated by Django 6.0.1 on 2026-02-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='preview_text',
            field=models.CharField(default='', max_length=280),
        ),
        migrations.AddField(
            model_name='user',
            name='id_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
