INSERT INTO api_user (
    id,
    password,
    last_login,
    is_superuser,
    username,
    is_staff,
    is_active,
    date_joined,
    first_name,
    middle_name,
    last_name,
    is_married,
    maiden_name,
    email,
    phone_number,
    batch,
    program,
    valid_id
  )
VALUES (
    'id:bigint',
    'password:character varying',
    'last_login:timestamp with time zone',
    is_superuser:boolean,
    'username:character varying',
    is_staff:boolean,
    is_active:boolean,
    'date_joined:timestamp with time zone',
    'first_name:character varying',
    'middle_name:character varying',
    'last_name:character varying',
    is_married:boolean,
    'maiden_name:character varying',
    'email:character varying',
    'phone_number:character varying',
    'batch:character varying',
    'program:character varying',
    'valid_id:character varying'
  );